# Configuration for crop yield prediction experiments

# Model & training
selected_bands: [0, 1, 3, 4, 5]     
input_channels: 5
batch_size: 32
num_epochs: 50
learning_rate: 0.0001
dropout_rate: 0.2

# Normalization
image_normalize_bands: true
yield_normalization: zscore         

# Fine-tuning
finetune_epochs: 10
finetune_lr: 0.00001
finetune_sizes: [0.1]     

# Clustering
num_clusters: 5                     
# Logging & saving
results_dir: "/workspace/crop_yield_raw/results"
save_checkpoints: true
early_stopping: true
early_stopping_patience: 5

# Hardware
num_workers: 2                      
pin_memory: true
